# /// script
# requires-python = ">=3.10"
# dependencies = ["Pillow"]
# ///
"""Generate overlay/emu_overlay_icons.h from source PNG icons.

Usage: uv run scripts/gen-icon-headers.py
"""

import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
RES_DIR = REPO / "src" / "nx-redux" / "skeleton" / "SYSTEM" / "res"
OUT = REPO / "overlay" / "emu_overlay_icons.h"

ICONS = [
    ("icon_a", "nav_button_a.png"),
    ("icon_b", "nav_button_b.png"),
    ("icon_dpad_h", "nav_dpad_horizontal.png"),
]


def png_to_argb(path: Path) -> tuple[int, int, list[int]]:
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    raw = img.tobytes("raw", "RGBA")
    pixels = []
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i], raw[i + 1], raw[i + 2], raw[i + 3]
        pixels.append((a << 24) | (r << 16) | (g << 8) | b)
    return w, h, pixels


def write_header(icons: list[tuple[str, int, int, list[int]]], out: Path) -> None:
    lines = [
        "/* Auto-generated by scripts/gen-icon-headers.py -- do not edit */",
        "#ifndef EMU_OVERLAY_ICONS_H",
        "#define EMU_OVERLAY_ICONS_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    for name, w, h, pixels in icons:
        NAME = name.upper()
        lines.append(f"#define {NAME}_W {w}")
        lines.append(f"#define {NAME}_H {h}")
        lines.append(f"static const uint32_t {name}_data[{w * h}] = {{")
        # Write 8 values per line
        for i in range(0, len(pixels), 8):
            chunk = pixels[i : i + 8]
            vals = ", ".join(f"0x{v:08X}" for v in chunk)
            comma = "," if i + 8 < len(pixels) else ""
            lines.append(f"    {vals}{comma}")
        lines.append("};")
        lines.append("")
    lines.append("#endif")
    lines.append("")
    out.write_text("\n".join(lines))


def main() -> None:
    icons = []
    for name, filename in ICONS:
        path = RES_DIR / filename
        if not path.exists():
            print(f"error: {path} not found", file=sys.stderr)
            sys.exit(1)
        w, h, pixels = png_to_argb(path)
        icons.append((name, w, h, pixels))
        print(f"  {filename}: {w}x{h} ({len(pixels)} pixels)")
    write_header(icons, OUT)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
